name: Windows-RDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 999999999999

    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/MREXw/Rdpacc/main/Start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/DinhPhuc/windows-rdp/main/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/DinhPhuc/windows-rdp/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/DinhPhuc/windows-rdp/main/loop.bat -OutFile loop.bat
    - name: Download Launcher.
      run: |
        Invoke-WebRequest https://unanimated-dittos.000webhostapp.com/Trash/telegram_icon-icons.com_72055.ico -OutFile "c:\tg.ico"
        Invoke-WebRequest https://unanimated-dittos.000webhostapp.com/Trash/sellix-logos-idEokOde4t.ico -OutFile "c:\sl.ico"
        Invoke-WebRequest https://unanimated-dittos.000webhostapp.com/Trash/tg.url -OutFile "TG Group.url"
        Invoke-WebRequest https://unanimated-dittos.000webhostapp.com/Trash/MRX-Hacking.url -OutFile "Sellix Store.url"
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Action Access RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.png D:\a\wallpaper.png
        copy wallpaper.bat D:\a\wallpaper.bat
        copy "TG Group.url" "C:\Users\Public\Desktop\TG Group.url"
        copy "Sellix Store.url" "C:\Users\Public\Desktop\Sellix Store.url"
    - name: Making tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect RDP CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c start.bat
    - name: Successful implementation! You can close the tab now.
      run: cmd /c loop.bat
